include: package:flutter_lints/flutter.yaml

linter:
  rules:
analyzer:
  exclude:
    - build/**
    - design_handoff_pulse_wire/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
